apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  namespace: foodbot
  labels:
    app: gateway-api
    component: backend
spec:
  type: ClusterIP
  selector:
    app: gateway-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api-headless
  namespace: foodbot
  labels:
    app: gateway-api
    component: backend
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: gateway-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
